# Generated by Django 4.2.1 on 2023-06-01 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0005_user_fee_amount_user_updated_alter_user_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
