# Generated by Django 4.2.1 on 2023-06-01 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0006_user_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
