# Generated by Django 4.2.1 on 2023-06-21 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0008_user_fee_paid_date_alter_user_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='blood_group',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_fee_paid',
            field=models.BooleanField(default=False),
        ),
    ]
