# Generated by Django 4.2.2 on 2023-07-06 17:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0013_user_added_by_user_fee_paid_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='fee_paid_by',
        ),
        migrations.AddField(
            model_name='user',
            name='marked_paid_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
